const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const INTERNAL_SERVER_ERROR = 500;
const STATUS_OK = 200;
const STATUS_CREATED = 201;

module.exports = {
  BAD_REQUEST,
  NOT_FOUND,
  INTERNAL_SERVER_ERROR,
  STATUS_OK,
  STATUS_CREATED,
};
